spring:
  profiles:
    active:
      - local
    group:
      common:
        - common-cron
        - common-mybatis
        - common-thymeleaf
      local:
        - database-local
        - common
      win:
        - database-local-win
        - common
#  config:
#    use-legacy-processing: true
