spring:
  profiles:
    active:
      - local
    group:
      local:
        - database-local
        - common
      win:
        - database-local-win
        - common
#  config:
#    use-legacy-processing: true
